### ISSUE TITLE
selected items do not show as selected

### ISSUE THREAD

**Issue by yochaig** [dnasir/jquery-cascading-dropdown#39]
Hello
I have created a 5 cascaded drop-downs with the plugin
for the 3rd 4th and 5th drop-down,s although I have marked "selected" items according to the value, it will show only the 1st value. 
the 2nd drop-down works OK

here is the code

http://jsfiddle.net/yochaig/xfwx22bb/7/

thank you in advance

**Comment by Tinman51** [comment]
I am seeing the same issue. Only the first drop down is getting the selected value set correctly  even though all the drop downs have the selected value set. (not the boolean selected, but the string|integer selected)

**Comment by yochaig** [comment]
just wanted to see if there is any comment or idea how to solve it. if not I will have to revert all the code :( which is something I really don't want to do....

**Comment by dnasir** [comment]
@yochaig Hi, sorry for the late response.

Firstly, I can't run the code you've provided on jsFiddle. Your service doesn't allow for cross domain ajax calls. You also don't have an error handler so the plugin does nothing in the event the Ajax call fails, and because the dropdown is dependent on another set of dropdowns, it is disabled on init, and stays that way because of the aforementioned reason.

I think this is a flaw in the plugin itself, as there should be some sort of fallback for this sort of situations. I'll try to improve on this.

Secondly, it seems like you're trying to build a cascading dropdown group that updates its dropdown list when the dependency changes value. If that's the case, other than the first dropdown, you don't want to include the default values for the other dropdowns. This is because the plugin will simply appends instead of replacing the values it fetches from your source (in this case, the JSON data from your web service).

For now, what I would do is set up the web service to return a set of results with one marked as selected.

    {
        "label": "Christian Theologians",
        "value": 4,
        "selected": true
    }

Also, since your service is already returning JSON data using the label/value format, you can probably just set the web service URL as the source value.

    source: "http://yochai.dyndns.info/hidden_law/ajax/items.asp"

I've updated your jsFiddle to reflect what I'm trying to tell you. I hope it helps. In the meantime, I'll work on improving the plugin to address the issues I've mentioned above.

http://jsfiddle.net/dzul1983/xfwx22bb/8/

**Comment by yochaig** [comment]
Thanks for the answer
few notes:
1. The HTML code i'm passed into jsfiddle was already calculated. to see the actual page you can see the page: http://yochai.dyndns.info/hidden_law/edit_paragraphs.asp?mode=add
This is dev environment so you can play around if you want.
As you can see I'm using call to the AJAX page dynamically.
In this page there is no pre-selected value hence everything is fine.

2. Once I have saved the form, I have all relevant field value known and I want the page itself to setup the selected value and not the json which include the generic list without the knowledge of the specific value per saved item. Hence the better solution in my case is to use the selected from the Select item and not as part of the supplied results (As I tried).
See example - if you look at the HTML, you can see I have the parameter for the selected option in the ASP page (which knows it) and not in the json results.
http://yochai.dyndns.info/hidden_law/edit_paragraphs.asp?mode=edit&paragraph_id=38

I hope you can change the plug-in to support this case.

Yochai

**Comment by yochaig** [comment]
Hi
Gentle reminder

Yochai

**Comment by dnasir** [comment]
Hi,

I can't access your page. All I'm seeing when I access the link you posted is this:

```
Microsoft VBScript runtime error '800a000d'

Type mismatch: '[string: ""]'

/hidden_law/includes/config.asp, line 53
```

From what I understand, when I load up the page after saving it once, it should show all the dropdowns with predefined values, correct? By default, the plugin will initialise the source function of a dropdown if the dropdown has a dependency and the requirements are met. So it seems like I need to implement some sort of flag that disables this on load. Let me know if I got this right.

**Comment by yochaig** [comment]
Hi
Hope that you will be able to access now.

indeed, when you load the page after it was saved once, all drop-downs should show the value which was selected upon saving the form.

for some reason although I mark selected: true on specific item it will not use it on the drop-downs (3rd - 5th)

Please note that although values have been chosen, I still want to allow the user to change the value and re-saving. such new selection on the 3rd drop-down for example should have an effect on the dependent drop-downs.
as such I'm not sure that disabling on load is the correct option, however I'm not experienced enough to judge.

Yochai

**Comment by yochaig** [comment]
Hi Dnasir
is there any update on the issue?

**Comment by dnasir** [comment]
@yochaig I wanted to try something out but I'm not able to access your web API methods from here, so I'll ask you to do it for me. For the following group,

```html
<div class="form-group">
	<label for="composition_id" class="col-sm-2 control-label">Composition:</label>
	<div class="col-sm-10">
		<select class="form-control" name="composition_id" id="composition_id" required>
			<option value="0"> - Select - </option>
		</select>
	</div>
</div>	
```
Please remove the value for the select option. The plugin converts the value to string, so "0" is not assumed to be false as it usually is in JavaScript, but actually as string with the value "0".

I'm not sure it will solve your problem, but it's the easiest solution I can think of at this point short of asking you to rewrite your web API to return the selected item in the JSON response.

I hope this helps.

**Comment by yochaig** [comment]
@dnasir 
I removed the value in 
http://yochai.dyndns.info/hidden_law/edit_paragraphs.asp?mode=edit&paragraph_id=38 

I'm aware of the option to add the value in the API, however in my case it is difficult as the API knows only the the full list of values and not aware to what happens in the specific cases.

Note that the selected value in the 2nd drop down does work, it stops working only in the 3rd to 5th drop down.
hence I'm wondering if you could can create a plug-in fix.

**Comment by dnasir** [comment]
@yochaig I see you've implemented a solution in the web service. I'll keep your case in mind, but fixing it will take some time.

**Comment by dnasir** [comment]
I'm closing this issue for now, as it seems like you've already come up with a solution for your problem.

**Comment by jgrosche** [comment]
I get the same problem, this plugin is good for creates, but does not handle multiple select boxes for  existing records very well at all.
